---
# - name: Dynamic add hosts to inventory
#   hosts: 127.0.0.1
#   connection: local
#   gather_facts: no
#   tasks:

    # - name: Add hosts from hosts_external_variable
    #   add_host:
    #     name: "{{ item }}"
    #     group: "computers"
    #   with_items: "{{ hosts_external_variable | default('127.0.0.1') }}"


- name: SETUP roles
  hosts: 127.0.0.1
  vars_files:
    - vars/common_vars.yml
  gather_facts: no
  roles:
    - install_nginx
    - install_php-fpm
